#!/usr/bin/env python3
"""Pack web/*.html (gzipped) into SHIV/web_ui.h so the pages ship inside the firmware.
Run after editing anything in web/:   python3 tools/embed_web.py"""
import gzip, os
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, ".."))
out = os.path.join(root, "SHIV", "web_ui.h")
pages = [("index.html", "PAGE_INDEX"), ("setup.html", "PAGE_SETUP")]
with open(out, "w") as f:
    f.write("// SHIV - web pages, gzipped (generated by tools/embed_web.py - edit web/*.html instead)\n#pragma once\n#include <Arduino.h>\nnamespace shiv {\n")
    for name, sym in pages:
        raw = open(os.path.join(root, "web", name), "rb").read()
        gz = gzip.compress(raw, 9, mtime=0)
        f.write(f"static const size_t {sym}_LEN = {len(gz)};\nstatic const uint8_t {sym}[] PROGMEM = {{\n")
        for i in range(0, len(gz), 24):
            f.write("  " + ",".join(str(b) for b in gz[i:i + 24]) + ",\n")
        f.write("};\n")
        print(f"{name}: {len(raw)} -> {len(gz)} bytes gz")
    f.write("}  // namespace shiv\n")
