#!/usr/bin/env python3
"""Generate SHIV/certs.h: the root CAs the stick trusts for HTTPS (Shopify).
Re-run if Shopify ever moves to a different certificate authority."""
import os
ROOTS = ["ISRG_Root_X1.pem", "ISRG_Root_X2.pem", "GTS_Root_R1.pem", "GTS_Root_R4.pem"]
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "..", "SHIV", "certs.h")
pem = ""
for r in ROOTS:
    pem += open(os.path.join("/etc/ssl/certs", r)).read().strip() + "\n"
with open(out, "w") as f:
    f.write("// SHIV - pinned root CAs (generated by tools/gen_certs.py): " + ", ".join(x[:-4] for x in ROOTS) + "\n")
    f.write("#pragma once\nnamespace shiv {\nstatic const char ROOT_CAS[] =\n")
    for line in pem.splitlines():
        f.write('  "' + line + '\\n"\n')
    f.write(";\n}  // namespace shiv\n")
print("wrote", os.path.normpath(out), len(pem), "bytes")
